version: "3.8"

services:
  trino:
    image: trinodb/trino:435
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./data:/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2G"
